parameters:
  google_client:
    client_id: '%env(GOOGLE_CLIENT_ID)%'
    project_id: '%env(GOOGLE_PROJECT_ID)%'
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
    redirect_uris: '%env(GOOGLE_REDIRECT_URIS)%'
    google_origins: '%env(GOOGLE_ORIGINS)%'

  github_client:
    client_id: '6f9eeb9c4ffe9aacbfdb'
    client_secret: '72ba1beee2649527a8f42d3b959143ab7a53b0e4'
    redirect_uris: 'http://googleclient:64640/getaccesstokengithub'

