parameters:
  google_client:
    client_id: '%env(GOOGLE_CLIENT_ID)%'
    project_id: '%env(GOOGLE_PROJECT_ID)%'
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
    redirect_uris: [ "https://www.marmits.com/oauth/googleauth/redirection.php" ]
    javascript_origins: [ "https://www.marmits.com" ]
