services:

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'



  Marmits\GoogleIdentification\Controller\IndexController:
    arguments: [
        '@service_container',
        '@Symfony\Component\HttpFoundation\RequestStack',
        '@Marmits\GoogleIdentification\Services\GoogleProvider',
        '@Marmits\GoogleIdentification\Services\GithubProvider'
    ]
    tags:
      - { name: controller.service_arguments }


  Marmits\GoogleIdentification\Controller\UserController:
    arguments: [
        '@service_container',
        '@Symfony\Component\HttpFoundation\RequestStack',
        '@Doctrine\ORM\EntityManagerInterface'
    ]
    tags:
      - { name: controller.service_arguments }


  Marmits\GoogleIdentification\Services\GoogleProvider:
    arguments:
      - googleclient_params: '%google_client%'

  Marmits\GoogleIdentification\Services\GithubProvider:
    arguments:
      - '@Symfony\Contracts\HttpClient\HttpClientInterface'
      - githubclient_params: '%github_client%'

