services:

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

  Marmits\GoogleIdentification\Repository\DatasRepository:
    arguments: [
        '@Doctrine\Persistence\ManagerRegistry',
    ]

  Marmits\GoogleIdentification\Services\UserApi:
    arguments: [
      '@Symfony\Component\HttpFoundation\RequestStack',
      '@Marmits\GoogleIdentification\Providers\GoogleProvider',
      '@Marmits\GoogleIdentification\Providers\GithubProvider'
    ]


  Marmits\GoogleIdentification\Entity\Datas:

  Marmits\GoogleIdentification\Controller\IndexController:
    arguments: [
        '@service_container',
        '@Symfony\Component\HttpFoundation\RequestStack',
        '@Marmits\GoogleIdentification\Services\UserApi',
    ]
    tags:
      - { name: controller.service_arguments }

  Marmits\GoogleIdentification\Controller\OauthController:
    arguments: [
      '@service_container',
      '@Symfony\Component\HttpFoundation\RequestStack',
      '@Marmits\GoogleIdentification\Providers\GoogleProvider',
      '@Marmits\GoogleIdentification\Providers\GithubProvider'
    ]
    tags:
      - { name: controller.service_arguments }



  Marmits\GoogleIdentification\Providers\AbstractProvider:
    arguments:
      - '@Symfony\Contracts\HttpClient\HttpClientInterface'

  Marmits\GoogleIdentification\Providers\GoogleProvider:
    arguments:
      - '@Symfony\Contracts\HttpClient\HttpClientInterface'
      - googleclient_params: '%google_client%'

  Marmits\GoogleIdentification\Providers\GithubProvider:
    arguments:
      - '@Symfony\Contracts\HttpClient\HttpClientInterface'
      - githubclient_params: '%github_client%'

  Marmits\GoogleIdentification\Services\Access:
    arguments:
      - private_params: '%private_access%'
      - '@Marmits\GoogleIdentification\Services\Encryption'

  Marmits\GoogleIdentification\Services\Encryption:
    arguments:
      - encryption_params: '%encryption%'

