services:


  Marmits\GoogleIdentification\Controller\IndexController:
    arguments: [
        '@Symfony\Component\DependencyInjection\ContainerInterface'
    ]
    tags:
      - { name: controller.service_arguments }

