services:

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'



  Marmits\Oauth2Identification\Services\UserApi:
    arguments: [
      '@Symfony\Component\HttpFoundation\RequestStack',
      '@Marmits\Oauth2Identification\Providers\GoogleProvider',
      '@Marmits\Oauth2Identification\Providers\GithubProvider'
    ]


  Marmits\Oauth2Identification\Controller\userApiController:
    arguments: [
      '@service_container',
      '@Marmits\Oauth2Identification\Services\UserApi',
    ]
    tags:
      - { name: controller.service_arguments }

  Marmits\Oauth2Identification\Controller\IndexController:
    arguments: [
        '@service_container',
        '@Symfony\Component\HttpFoundation\RequestStack',
        '@Marmits\Oauth2Identification\Services\UserApi',
    ]
    tags:
      - { name: controller.service_arguments }

  Marmits\Oauth2Identification\Controller\OauthController:
    arguments: [
      '@service_container',
      '@Marmits\Oauth2Identification\Providers\AccessTokenProcess',
    ]
    tags:
      - { name: controller.service_arguments }


  Marmits\Oauth2Identification\Providers\AccessTokenProcess:
    arguments: [
      '@Symfony\Component\HttpFoundation\RequestStack',
      '@Marmits\Oauth2Identification\Providers\GoogleProvider',
      '@Marmits\Oauth2Identification\Providers\GithubProvider',
      '@Marmits\Oauth2Identification\Services\UserApi'
    ]


  Marmits\Oauth2Identification\Providers\AbstractProvider:
    arguments:
      - '@Symfony\Contracts\HttpClient\HttpClientInterface'

  Marmits\Oauth2Identification\Providers\GoogleProvider:
    arguments:
      - '@Symfony\Contracts\HttpClient\HttpClientInterface'
      - googleclient_params: '%google_client%'

  Marmits\Oauth2Identification\Providers\GithubProvider:
    arguments:
      - '@Symfony\Contracts\HttpClient\HttpClientInterface'
      - githubclient_params: '%github_client%'

  Marmits\Oauth2Identification\Services\Access:
    arguments:
      - private_params: '%private_access%'
      - '@Marmits\Oauth2Identification\Services\Encryption'

  Marmits\Oauth2Identification\Services\Encryption:
    arguments:
      - encryption_params: '%encryption%'

