services:

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

  Marmits\Oauth2Identification\Entity\OauthUser:
  Marmits\Oauth2Identification\Repository\OauthUserRepository:
    arguments:
      - '@Doctrine\Persistence\ManagerRegistry'

  _instanceof:
    Marmits\Oauth2Identification\Providers\ProviderInterface:
      tags: [ 'marmits.oauth_provider' ]

  Marmits\Oauth2Identification\Providers\Provider:
    arguments:
      - !tagged_iterator marmits.oauth_provider

  Marmits\Oauth2Identification\Providers\AbstractProvider:
    arguments:
      - '@Symfony\Contracts\HttpClient\HttpClientInterface'

  Marmits\Oauth2Identification\Providers\GoogleProvider:
    arguments:
      - '@Symfony\Component\HttpFoundation\RequestStack'
      - '@Marmits\Oauth2Identification\Services\UserApi'
      - '@Symfony\Contracts\HttpClient\HttpClientInterface'
      - params: '%google_client%'

  Marmits\Oauth2Identification\Providers\GithubProvider:
    arguments:
      - '@Symfony\Component\HttpFoundation\RequestStack'
      - '@Marmits\Oauth2Identification\Services\UserApi'
      - '@Symfony\Contracts\HttpClient\HttpClientInterface'
      - params: '%github_client%'

  Marmits\Oauth2Identification\Services\UserApi:
    arguments: [
      '@Symfony\Component\HttpFoundation\RequestStack',
      '@Marmits\Oauth2Identification\Providers\Provider',
      '@Marmits\Oauth2Identification\Repository\OauthUserRepository',
      '@Marmits\Oauth2Identification\Services\Encryption'
    ]

  Marmits\Oauth2Identification\Controller\userApiController:
    arguments: [
      '@service_container',
      '@Marmits\Oauth2Identification\Services\UserApi',
    ]
    tags: [ 'controller.service_arguments','container.service_subscriber' ]
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]

  Marmits\Oauth2Identification\Controller\IndexController:
    arguments: [
        '@service_container',
        '@Symfony\Component\HttpFoundation\RequestStack',
        '@Marmits\Oauth2Identification\Services\UserApi',
    ]
    tags: [ 'controller.service_arguments','container.service_subscriber' ]
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]

  Marmits\Oauth2Identification\Controller\OauthController:
    arguments: [
      '@service_container',
      '@Marmits\Oauth2Identification\Providers\Provider',
    ]
    tags: [ 'controller.service_arguments','container.service_subscriber' ]
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]



  Marmits\Oauth2Identification\Services\Encryption:
    arguments:
      - encryption_params: '%encryption%'

